### PR TITLE
Fix connect example

### PR DESCRIPTION
**Pull request by vjousse**
I was going through the README and noticed that the proposed `connect` function doesn't compile out of the box.

Not sure if it's the best way to fix it, but it works. Don't hesitate if there is a better way!

Cheers

### CODE REVIEW

**Review by jwoertink — COMMENTED** [review]
I'm ok with this change since it does take the example from not compiling directly, to at least working; however, should this example be a little less "Lucky" focused? Or should we just go all in on the Lucky example? If the latter, then it should use [UserToken](https://github.com/luckyframework/lucky_cli/blob/98d5bf099723a28b40c9052d4b534c1ecc10afc7/src/api_authentication_app_skeleton/src/models/user_token.cr#L16) since that's a cleaner way to handle it. If we take out the Lucky based code, then we should rescue from `JWT::Error` instead of `Avram::RecordNotFoundError`

What are your thoughts @vjousse ?

**Comment by vjousse** [comment]
Well, to be honest, I don't see the point of not going all in on the Lucky example for now. At least, it gives people a real world example to build on.
I would prefer to give an example for each and every "big" crystal framework rather than giving something generic that is usable in none.

What do you think?

**Comment by jwoertink** [comment]
That makes sense to me. I've seen several shards do that, and it makes it easier to integrate than to think "ok, that works with raw Crystal, but how about in Lucky/Amber,etc..."

In that case, the example becomes a lot more simple:

```crystal
def connect
  UserAuthToken.decode_user_id(token.to_s).try do |user_id|
    self.identifier = user_id.to_s
    self.current_user =  UserQuery.find(user_id)
  end
end
```

**Review by jwoertink — APPROVED** [review]
Sweet! Yeah, this looks much cleaner for a Lucky example. Thanks for updating this 👍

**Comment by fernandes** [comment]
thank you @vjousse ! :D

**Pull request merged**
