### PR TITLE
Move Redis logic to a backend abstraction

### PR DESCRIPTION
**Pull request by mjeffrey18**
If we plan to swap to the new [Redis shard](https://github.com/jgaskins/redi), we can ask folk to use the preferred Redis shard but allow them to still use the previous shard.
This PR also paves the way to having Postgres and other backends.

### CODE REVIEW

**Comment by mjeffrey18** [comment]
@jwoertink / @jgaskins this PR is still a WIP, I'll jump back on this tomorrow and finish it up.
Thoughts so far?

**Comment by jwoertink** [comment]
I like the direction of a server being instantiated, and it sets up the backend.

Overall, I dig the concept. I guess for this to actually work, then this shard can't include either as a dependency. We would have to instruct users installing cable "If you use shard A, then add that to your shard.yml, and require file_A, but if you use shard B, then add that one to your shard.yml, and require shard_B". 

This shard had a similar problem:

https://github.com/wyhaines/opentelemetry-instrumentation.cr/blob/7d83b9a53c9540fbc159f06eeed5d4bdad5c4377/shard.yml#L25-L30

I'll try and read through again later and see if anything else comes to mind. Great work on this! I appreciate all the help and contributions :raised_hands:

**Comment by mjeffrey18** [comment]
@jwoertink this one is ready. I suggest we merge this one first - https://github.com/cable-cr/cable/pull/55
I'll try to finish that up this week.

**Comment by jwoertink** [comment]
Looks like there's a conflict now that will need to be resolved, then it'll be good :+1:

**Comment by jwoertink** [comment]
This is looking good! Did you have more changes for this @mjeffrey18 or do you think this is ready to go?

**Comment by mjeffrey18** [comment]
hey @jwoertink, this PR is ready now. I think we can do a 0.3 release after this is merged.

I have a few improvements to make (I'll try to finish next weekend)
- Allow [error reporting hooks](https://github.com/cable-cr/cable/pull/57)
- Allow optional JSON logs
- Allow optional tracing hooks
- Renaming and refactoring to make the code more fluent in understanding and modifying.

We can release those in the next release tho.

Let me know your thoughts.

**Comment by fernandes** [comment]
hey @mjeffrey18 👋 

was curious about _Renaming and refactoring to make the code more fluent in understanding and modifying._

would love to hear your thoughts how we can improve it 😄 

thank you

**Review by jwoertink — APPROVED** [review]
:rocket:

**Review by fernandes — APPROVED** [review]

**Pull request merged**
